// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/backend (interfaces: ObjectBackend)
//
// Generated by this command:
//
//	mockgen -destination=mock_backend.go -package=backendtest github.com/afreidah/s3-orchestrator/internal/backend ObjectBackend
//

package backendtest

import (
	context "context"
	io "io"
	reflect "reflect"

	backend "github.com/afreidah/s3-orchestrator/internal/backend"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectBackend is a mock of ObjectBackend interface.
type MockObjectBackend struct {
	ctrl     *gomock.Controller
	recorder *MockObjectBackendMockRecorder
	isgomock struct{}
}

// MockObjectBackendMockRecorder is the mock recorder for MockObjectBackend.
type MockObjectBackendMockRecorder struct {
	mock *MockObjectBackend
}

// NewMockObjectBackend creates a new mock instance.
func NewMockObjectBackend(ctrl *gomock.Controller) *MockObjectBackend {
	mock := &MockObjectBackend{ctrl: ctrl}
	mock.recorder = &MockObjectBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectBackend) EXPECT() *MockObjectBackendMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockObjectBackend) DeleteObject(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectBackendMockRecorder) DeleteObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectBackend)(nil).DeleteObject), ctx, key)
}

// GetObject mocks base method.
func (m *MockObjectBackend) GetObject(ctx context.Context, key, rangeHeader string) (*backend.GetObjectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, key, rangeHeader)
	ret0, _ := ret[0].(*backend.GetObjectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockObjectBackendMockRecorder) GetObject(ctx, key, rangeHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockObjectBackend)(nil).GetObject), ctx, key, rangeHeader)
}

// HeadObject mocks base method.
func (m *MockObjectBackend) HeadObject(ctx context.Context, key string) (*backend.HeadObjectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadObject", ctx, key)
	ret0, _ := ret[0].(*backend.HeadObjectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockObjectBackendMockRecorder) HeadObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadObject", reflect.TypeOf((*MockObjectBackend)(nil).HeadObject), ctx, key)
}

// PutObject mocks base method.
func (m *MockObjectBackend) PutObject(ctx context.Context, key string, body io.Reader, size int64, contentType string, metadata map[string]string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, key, body, size, contentType, metadata)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockObjectBackendMockRecorder) PutObject(ctx, key, body, size, contentType, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockObjectBackend)(nil).PutObject), ctx, key, body, size, contentType, metadata)
}
