// -------------------------------------------------------------------------------
// Admin API - Provisioning DTOs
//
// Author: Alex Freidah
//
// Wire types for bucket, user, credential and grant administration, shared by
// the handler and its clients. Kept in the leaf adminapi package so the server
// and the out-of-process client depend on one definition.
//
// Every listed entry carries the source that declared it, because that is what
// tells a caller whether it can be changed: a config-declared entry is visible
// and read-only. No listing carries a secret; the one place a secret appears is
// the response to the request that minted it.
// -------------------------------------------------------------------------------

package adminapi

// Source values an entry carries, naming which of the two places declared it.
const (
	SourceConfig = "config"
	SourceStore  = "store"
)

// Bucket is one virtual bucket as the API reports it.
type Bucket struct {
	Name                string     `json:"name"`
	MaxMultipartUploads int        `json:"max_multipart_uploads"`
	CORS                []CORSRule `json:"cors,omitempty"`
	Source              string     `json:"source"`
}

// CORSRule mirrors the S3 CORSRule shape a bucket carries.
type CORSRule struct {
	AllowedOrigins []string `json:"allowed_origins"`
	AllowedMethods []string `json:"allowed_methods"`
	AllowedHeaders []string `json:"allowed_headers,omitempty"`
	ExposeHeaders  []string `json:"expose_headers,omitempty"`
	MaxAge         int      `json:"max_age,omitempty"`
}

// User is one identity as the API reports it, with what it reaches.
//
// Buckets stays a plain name list so a caller that only asks which buckets an
// identity reaches does not have to walk an object. Grants is the whole
// picture: the bucket reach with what each carries, plus the control-plane
// resources the identity holds. A bucket wildcard appears as the buckets it
// expands to, which is what the request path will actually answer.
type User struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Buckets []string `json:"buckets"`
	Grants  []Grant  `json:"grants"`
	Source  string   `json:"source"`
}

// Grant is one resource a user reaches and the permissions that reach carries.
// Name is empty on an orchestrator grant, which names no one thing.
type Grant struct {
	Kind        string   `json:"kind"`
	Name        string   `json:"name,omitempty"`
	Permissions []string `json:"permissions"`
}

// Credential is one keypair as the API reports it. The secret is deliberately
// absent: it is returned once, by the request that minted it, and never read
// back.
type Credential struct {
	AccessKeyID string `json:"access_key_id"`
	UserID      string `json:"user_id"`
	Label       string `json:"label,omitempty"`
	Source      string `json:"source"`
}

// Notice is something the merge of the two sources found that an operator
// should see and that does not stop the instance serving.
type Notice struct {
	Kind   string `json:"kind"`
	Detail string `json:"detail"`
}

// ProvisioningResponse is everything a deployment declares, from both sources.
// One response rather than four endpoints, because the four are only meaningful
// together: a credential names a user, and a user is only useful for the
// buckets it reaches.
type ProvisioningResponse struct {
	Buckets     []Bucket     `json:"buckets"`
	Users       []User       `json:"users"`
	Credentials []Credential `json:"credentials"`
	Notices     []Notice     `json:"notices,omitempty"`
}

// CreateBucketRequest declares a virtual bucket. MaxMultipartUploads of 0 means
// unlimited, matching the config field it mirrors.
type CreateBucketRequest struct {
	Name                string     `json:"name"`
	MaxMultipartUploads int        `json:"max_multipart_uploads,omitempty"`
	CORS                []CORSRule `json:"cors,omitempty"`
}

// UpdateBucketRequest declares what a bucket carries. The name is in the path:
// it identifies the bucket and the objects stored under it, so it is not
// something this can change.
//
// The bucket is replaced rather than merged into. Omitting CORS removes the
// rules the bucket had, and MaxMultipartUploads of 0 means unlimited, as it
// does on create.
type UpdateBucketRequest struct {
	MaxMultipartUploads int        `json:"max_multipart_uploads,omitempty"`
	CORS                []CORSRule `json:"cors,omitempty"`
}

// CreateUserRequest declares an identity credentials can be issued against. The
// id is generated by the server, so it is unique and survives a rename.
type CreateUserRequest struct {
	Name string `json:"name"`
}

// CreateCredentialRequest registers a keypair against an existing user. The
// user is required: a keypair with no owner is a credential nobody can account
// for. Label is free text an operator uses to say what holds it.
//
// AccessKeyID and SecretAccessKey are for a caller that already holds the
// keypair, which is the shape anything driving this declaratively is in: the
// secret is generated wherever that caller keeps its secrets and recorded here.
// Both are required together, and omitting both mints one instead.
type CreateCredentialRequest struct {
	UserID          string `json:"user_id"`
	Label           string `json:"label,omitempty"`
	AccessKeyID     string `json:"access_key_id,omitempty"`
	SecretAccessKey string `json:"secret_access_key,omitempty"`
}

// CreateCredentialResponse carries the keypair the request produced.
//
// A minted secret crosses the wire here and nowhere else: it is not stored
// anywhere it can be read back, so a caller that loses it issues a replacement
// rather than recovering this one. A supplied secret is echoed rather than
// withheld, so one response shape covers both and a caller can confirm what was
// recorded against what it sent.
type CreateCredentialResponse struct {
	AccessKeyID     string `json:"access_key_id"`
	SecretAccessKey string `json:"secret_access_key"`
	UserID          string `json:"user_id"`
	Label           string `json:"label,omitempty"`
}

// RenameUserRequest changes the name an operator reads an identity by. The ID
// is in the path and does not move: credentials and grants reference it.
type RenameUserRequest struct {
	Name string `json:"name"`
}

// SetGrantRequest declares exactly what a user reaches on one resource. The
// user and resource are in the path; an empty Permissions is refused rather
// than read as every permission, because a declaration saying nothing is more
// likely a mistake than a request for full access.
type SetGrantRequest struct {
	Permissions []string `json:"permissions"`
}

// CreateGrantRequest lets one user reach one resource, with the permissions
// that reach carries.
//
// Kind defaults to "bucket", so a caller onboarding a client onto a bucket
// names only the bucket. Name may be "*" for every resource of the kind, and is
// omitted on an orchestrator grant. An empty Permissions means every permission
// valid on the kind.
type CreateGrantRequest struct {
	UserID      string   `json:"user_id"`
	Kind        string   `json:"kind,omitempty"`
	Name        string   `json:"name,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
}

// ProvisioningOperationResponse acknowledges a mutation, naming what it
// changed so a caller replaying a log can tell one call from the next.
type ProvisioningOperationResponse struct {
	Status   string `json:"status"`
	Bucket   string `json:"bucket,omitempty"`
	Resource string `json:"resource,omitempty"`
	UserID   string `json:"user_id,omitempty"`
	UserName string `json:"user_name,omitempty"`
}
