// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/proxy/dashboard (interfaces: FleetView,DrainProgressReader,UsageReader)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=dashboard github.com/afreidah/s3-orchestrator/internal/proxy/dashboard FleetView,DrainProgressReader,UsageReader
//

// Package dashboard is a generated GoMock package.
package dashboard

import (
	context "context"
	reflect "reflect"

	backend "github.com/afreidah/s3-orchestrator/internal/backend"
	drain "github.com/afreidah/s3-orchestrator/internal/proxy/drain"
	s3op "github.com/afreidah/s3-orchestrator/internal/s3op"
	core "github.com/afreidah/s3-orchestrator/internal/store/core"
	gomock "go.uber.org/mock/gomock"
)

// MockFleetView is a mock of FleetView interface.
type MockFleetView struct {
	ctrl     *gomock.Controller
	recorder *MockFleetViewMockRecorder
	isgomock struct{}
}

// MockFleetViewMockRecorder is the mock recorder for MockFleetView.
type MockFleetViewMockRecorder struct {
	mock *MockFleetView
}

// NewMockFleetView creates a new mock instance.
func NewMockFleetView(ctrl *gomock.Controller) *MockFleetView {
	mock := &MockFleetView{ctrl: ctrl}
	mock.recorder = &MockFleetViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFleetView) EXPECT() *MockFleetViewMockRecorder {
	return m.recorder
}

// BackendOrder mocks base method.
func (m *MockFleetView) BackendOrder() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackendOrder")
	ret0, _ := ret[0].([]string)
	return ret0
}

// BackendOrder indicates an expected call of BackendOrder.
func (mr *MockFleetViewMockRecorder) BackendOrder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendOrder", reflect.TypeOf((*MockFleetView)(nil).BackendOrder))
}

// Backends mocks base method.
func (m *MockFleetView) Backends() map[string]backend.ObjectBackend {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backends")
	ret0, _ := ret[0].(map[string]backend.ObjectBackend)
	return ret0
}

// Backends indicates an expected call of Backends.
func (mr *MockFleetViewMockRecorder) Backends() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backends", reflect.TypeOf((*MockFleetView)(nil).Backends))
}

// IsDraining mocks base method.
func (m *MockFleetView) IsDraining(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDraining", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDraining indicates an expected call of IsDraining.
func (mr *MockFleetViewMockRecorder) IsDraining(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDraining", reflect.TypeOf((*MockFleetView)(nil).IsDraining), name)
}

// MockDrainProgressReader is a mock of DrainProgressReader interface.
type MockDrainProgressReader struct {
	ctrl     *gomock.Controller
	recorder *MockDrainProgressReaderMockRecorder
	isgomock struct{}
}

// MockDrainProgressReaderMockRecorder is the mock recorder for MockDrainProgressReader.
type MockDrainProgressReaderMockRecorder struct {
	mock *MockDrainProgressReader
}

// NewMockDrainProgressReader creates a new mock instance.
func NewMockDrainProgressReader(ctrl *gomock.Controller) *MockDrainProgressReader {
	mock := &MockDrainProgressReader{ctrl: ctrl}
	mock.recorder = &MockDrainProgressReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrainProgressReader) EXPECT() *MockDrainProgressReaderMockRecorder {
	return m.recorder
}

// GetDrainProgress mocks base method.
func (m *MockDrainProgressReader) GetDrainProgress(ctx context.Context, name string) (*drain.Progress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDrainProgress", ctx, name)
	ret0, _ := ret[0].(*drain.Progress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrainProgress indicates an expected call of GetDrainProgress.
func (mr *MockDrainProgressReaderMockRecorder) GetDrainProgress(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrainProgress", reflect.TypeOf((*MockDrainProgressReader)(nil).GetDrainProgress), ctx, name)
}

// MockUsageReader is a mock of UsageReader interface.
type MockUsageReader struct {
	ctrl     *gomock.Controller
	recorder *MockUsageReaderMockRecorder
	isgomock struct{}
}

// MockUsageReaderMockRecorder is the mock recorder for MockUsageReader.
type MockUsageReaderMockRecorder struct {
	mock *MockUsageReader
}

// NewMockUsageReader creates a new mock instance.
func NewMockUsageReader(ctrl *gomock.Controller) *MockUsageReader {
	mock := &MockUsageReader{ctrl: ctrl}
	mock.recorder = &MockUsageReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageReader) EXPECT() *MockUsageReaderMockRecorder {
	return m.recorder
}

// BackendsWithinLimits mocks base method.
func (m *MockUsageReader) BackendsWithinLimits(order []string, ops []s3op.Operation, egress, ingress int64) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackendsWithinLimits", order, ops, egress, ingress)
	ret0, _ := ret[0].([]string)
	return ret0
}

// BackendsWithinLimits indicates an expected call of BackendsWithinLimits.
func (mr *MockUsageReaderMockRecorder) BackendsWithinLimits(order, ops, egress, ingress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendsWithinLimits", reflect.TypeOf((*MockUsageReader)(nil).BackendsWithinLimits), order, ops, egress, ingress)
}

// GetLimits mocks base method.
func (m *MockUsageReader) GetLimits() map[string]core.UsageLimits {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimits")
	ret0, _ := ret[0].(map[string]core.UsageLimits)
	return ret0
}

// GetLimits indicates an expected call of GetLimits.
func (mr *MockUsageReaderMockRecorder) GetLimits() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimits", reflect.TypeOf((*MockUsageReader)(nil).GetLimits))
}
