// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/proxy/expiry (interfaces: ObjectDeleter)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=expiry github.com/afreidah/s3-orchestrator/internal/proxy/expiry ObjectDeleter
//

// Package expiry is a generated GoMock package.
package expiry

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockObjectDeleter is a mock of ObjectDeleter interface.
type MockObjectDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockObjectDeleterMockRecorder
	isgomock struct{}
}

// MockObjectDeleterMockRecorder is the mock recorder for MockObjectDeleter.
type MockObjectDeleterMockRecorder struct {
	mock *MockObjectDeleter
}

// NewMockObjectDeleter creates a new mock instance.
func NewMockObjectDeleter(ctrl *gomock.Controller) *MockObjectDeleter {
	mock := &MockObjectDeleter{ctrl: ctrl}
	mock.recorder = &MockObjectDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectDeleter) EXPECT() *MockObjectDeleterMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockObjectDeleter) DeleteObject(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectDeleterMockRecorder) DeleteObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectDeleter)(nil).DeleteObject), ctx, key)
}
