// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BackendQuota struct {
	BackendName string
	BytesUsed   int64
	BytesLimit  int64
	UpdatedAt   pgtype.Timestamptz
	OrphanBytes int64
}

type BackendUsage struct {
	BackendName  string
	Period       string
	ApiRequests  int64
	EgressBytes  int64
	IngressBytes int64
	UpdatedAt    pgtype.Timestamptz
}

type CleanupDlq struct {
	ID              int64
	OriginalID      int64
	BackendName     string
	ObjectKey       string
	Reason          string
	SizeBytes       int64
	Attempts        int32
	FirstEnqueuedAt pgtype.Timestamptz
	MovedAt         pgtype.Timestamptz
	LastError       *string
}

type CleanupQueue struct {
	ID          int64
	BackendName string
	ObjectKey   string
	Reason      string
	CreatedAt   pgtype.Timestamptz
	NextRetry   pgtype.Timestamptz
	Attempts    int32
	LastError   *string
	SizeBytes   int64
	ClaimedAt   pgtype.Timestamptz
	ClaimedBy   *string
}

type MultipartPart struct {
	UploadID      string
	PartNumber    int32
	Etag          string
	SizeBytes     int64
	CreatedAt     pgtype.Timestamptz
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
}

type MultipartUpload struct {
	UploadID      string
	ObjectKey     string
	BackendName   string
	ContentType   *string
	CreatedAt     pgtype.Timestamptz
	Metadata      []byte
	EncryptionKey []byte
	KeyID         *string
}

type NotificationOutbox struct {
	ID          int64
	EventType   string
	Payload     []byte
	EndpointUrl string
	CreatedAt   pgtype.Timestamptz
	NextRetry   pgtype.Timestamptz
	Attempts    int32
	LastError   *string
}

type ObjectLocation struct {
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	CreatedAt            pgtype.Timestamptz
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
}

type PendingObject struct {
	IntentID             string
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CreatedAt            pgtype.Timestamptz
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
}
