// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: objects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backendObjectStats = `-- name: BackendObjectStats :one
SELECT COUNT(*) AS object_count, COALESCE(SUM(size_bytes), 0)::bigint AS total_bytes
FROM object_locations
WHERE backend_name = $1
`

type BackendObjectStatsRow struct {
	ObjectCount int64
	TotalBytes  int64
}

func (q *Queries) BackendObjectStats(ctx context.Context, backendName string) (BackendObjectStatsRow, error) {
	row := q.db.QueryRow(ctx, backendObjectStats, backendName)
	var i BackendObjectStatsRow
	err := row.Scan(&i.ObjectCount, &i.TotalBytes)
	return i, err
}

const checkObjectExistsOnBackend = `-- name: CheckObjectExistsOnBackend :one
SELECT EXISTS(
    SELECT 1 FROM object_locations
    WHERE object_key = $1 AND backend_name = $2
) AS exists
`

type CheckObjectExistsOnBackendParams struct {
	ObjectKey   string
	BackendName string
}

func (q *Queries) CheckObjectExistsOnBackend(ctx context.Context, arg CheckObjectExistsOnBackendParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkObjectExistsOnBackend, arg.ObjectKey, arg.BackendName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteObjectCopies = `-- name: DeleteObjectCopies :exec
DELETE FROM object_locations
WHERE object_key = $1
`

func (q *Queries) DeleteObjectCopies(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, deleteObjectCopies, objectKey)
	return err
}

const deleteObjectFromBackend = `-- name: DeleteObjectFromBackend :exec
DELETE FROM object_locations
WHERE object_key = $1 AND backend_name = $2
`

type DeleteObjectFromBackendParams struct {
	ObjectKey   string
	BackendName string
}

func (q *Queries) DeleteObjectFromBackend(ctx context.Context, arg DeleteObjectFromBackendParams) error {
	_, err := q.db.Exec(ctx, deleteObjectFromBackend, arg.ObjectKey, arg.BackendName)
	return err
}

const deleteObjectLocationsByBackend = `-- name: DeleteObjectLocationsByBackend :exec
DELETE FROM object_locations WHERE backend_name = $1
`

func (q *Queries) DeleteObjectLocationsByBackend(ctx context.Context, backendName string) error {
	_, err := q.db.Exec(ctx, deleteObjectLocationsByBackend, backendName)
	return err
}

const deleteObjectsByKeys = `-- name: DeleteObjectsByKeys :exec
DELETE FROM object_locations
WHERE object_key = ANY($1::text[])
`

// Deletes every row whose object_key is in the supplied list. Caller
// must have already locked the rows via GetCopiesForKeysForUpdate.
func (q *Queries) DeleteObjectsByKeys(ctx context.Context, objectKeys []string) error {
	_, err := q.db.Exec(ctx, deleteObjectsByKeys, objectKeys)
	return err
}

const getAllObjectLocations = `-- name: GetAllObjectLocations :many
SELECT object_key, backend_name, size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_version, logical_size, created_at
FROM object_locations
WHERE object_key = $1
ORDER BY created_at ASC
`

type GetAllObjectLocationsRow struct {
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) GetAllObjectLocations(ctx context.Context, objectKey string) ([]GetAllObjectLocationsRow, error) {
	rows, err := q.db.Query(ctx, getAllObjectLocations, objectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllObjectLocationsRow{}
	for rows.Next() {
		var i GetAllObjectLocationsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.ContentHash,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionVersion,
			&i.LogicalSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCopiesForKeysForUpdate = `-- name: GetCopiesForKeysForUpdate :many
SELECT object_key, backend_name, size_bytes
FROM object_locations
WHERE object_key = ANY($1::text[])
FOR UPDATE
`

type GetCopiesForKeysForUpdateRow struct {
	ObjectKey   string
	BackendName string
	SizeBytes   int64
}

// Returns (object_key, backend_name, size_bytes) for every row matching
// a key in the supplied list, locked FOR UPDATE so the same transaction
// can delete the rows and decrement the corresponding backend quotas
// atomically. Used by the batch-delete path so an N-key request is one
// transaction instead of N.
func (q *Queries) GetCopiesForKeysForUpdate(ctx context.Context, objectKeys []string) ([]GetCopiesForKeysForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getCopiesForKeysForUpdate, objectKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCopiesForKeysForUpdateRow{}
	for rows.Next() {
		var i GetCopiesForKeysForUpdateRow
		if err := rows.Scan(&i.ObjectKey, &i.BackendName, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectoryStats = `-- name: GetDirectoryStats :many
SELECT
    (CASE WHEN position('/' IN substr(object_key, $1::int)) > 0
         THEN substr(object_key, $1::int,
              position('/' IN substr(object_key, $1::int)))
         ELSE substr(object_key, $1::int)
    END)::text AS name,
    (CASE WHEN position('/' IN substr(object_key, $1::int)) > 0
         THEN true ELSE false
    END)::boolean AS is_dir,
    COUNT(DISTINCT object_key) AS file_count,
    COALESCE(SUM(size_bytes), 0)::bigint AS total_size
FROM object_locations
WHERE object_key LIKE $2::text || '%' ESCAPE '\'
  AND length(object_key) >= $1::int
GROUP BY name, is_dir
ORDER BY is_dir DESC, name ASC
`

type GetDirectoryStatsParams struct {
	NameStart int32
	Prefix    string
}

type GetDirectoryStatsRow struct {
	Name      string
	IsDir     bool
	FileCount int64
	TotalSize int64
}

// Aggregate count and size for immediate children of a directory prefix.
// Directories (containing a '/') and files are distinguished by is_dir.
// file_count counts distinct object_keys (logical files); total_size sums
// every replica row in object_locations so directory totals reflect real
// physical storage consumption, matching the Storage Summary semantics.
// @prefix is LIKE-escaped for the WHERE match; @name_start is the 1-based
// character position where the child name begins (len(unescaped prefix) + 1),
// so escaped wildcards (e.g. '\_') don't shift the substring cut point.
func (q *Queries) GetDirectoryStats(ctx context.Context, arg GetDirectoryStatsParams) ([]GetDirectoryStatsRow, error) {
	rows, err := q.db.Query(ctx, getDirectoryStats, arg.NameStart, arg.Prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDirectoryStatsRow{}
	for rows.Next() {
		var i GetDirectoryStatsRow
		if err := rows.Scan(
			&i.Name,
			&i.IsDir,
			&i.FileCount,
			&i.TotalSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingCopiesForUpdate = `-- name: GetExistingCopiesForUpdate :many
SELECT backend_name, size_bytes, created_at
FROM object_locations
WHERE object_key = $1
FOR UPDATE
`

type GetExistingCopiesForUpdateRow struct {
	BackendName string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetExistingCopiesForUpdate(ctx context.Context, objectKey string) ([]GetExistingCopiesForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getExistingCopiesForUpdate, objectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExistingCopiesForUpdateRow{}
	for rows.Next() {
		var i GetExistingCopiesForUpdateRow
		if err := rows.Scan(&i.BackendName, &i.SizeBytes, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObjectBackendsForKeys = `-- name: GetObjectBackendsForKeys :many
SELECT object_key, backend_name
FROM object_locations
WHERE object_key = ANY($1::text[])
`

type GetObjectBackendsForKeysRow struct {
	ObjectKey   string
	BackendName string
}

// Returns (object_key, backend_name) for every object_locations row whose
// object_key is in the supplied list. Used by the rebalancer planner to
// determine which backends already hold a copy of each candidate key in a
// batch, replacing the per-key GetAllObjectLocations N+1 pattern.
func (q *Queries) GetObjectBackendsForKeys(ctx context.Context, objectKeys []string) ([]GetObjectBackendsForKeysRow, error) {
	rows, err := q.db.Query(ctx, getObjectBackendsForKeys, objectKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetObjectBackendsForKeysRow{}
	for rows.Next() {
		var i GetObjectBackendsForKeysRow
		if err := rows.Scan(&i.ObjectKey, &i.BackendName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObjectsWithoutHash = `-- name: GetObjectsWithoutHash :many
SELECT object_key, backend_name, size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_version, logical_size, created_at
FROM object_locations
WHERE content_hash IS NULL
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type GetObjectsWithoutHashParams struct {
	Limit  int32
	Offset int32
}

type GetObjectsWithoutHashRow struct {
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
	CreatedAt            pgtype.Timestamptz
}

// Return object locations that have no content hash, for backfill.
func (q *Queries) GetObjectsWithoutHash(ctx context.Context, arg GetObjectsWithoutHashParams) ([]GetObjectsWithoutHashRow, error) {
	rows, err := q.db.Query(ctx, getObjectsWithoutHash, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetObjectsWithoutHashRow{}
	for rows.Next() {
		var i GetObjectsWithoutHashRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.ContentHash,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionVersion,
			&i.LogicalSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomHashedObjects = `-- name: GetRandomHashedObjects :many
SELECT object_key, backend_name, size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_version, logical_size, created_at
FROM object_locations TABLESAMPLE BERNOULLI (10)
WHERE content_hash IS NOT NULL
LIMIT $1
`

type GetRandomHashedObjectsRow struct {
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
	CreatedAt            pgtype.Timestamptz
}

// Return random object locations that have a content hash, for scrubber
// verification. Uses TABLESAMPLE to avoid a full table sort, then filters
// and limits. The sample percentage is generous (10%) to ensure enough rows
// pass the WHERE filter; the LIMIT caps the final result.
func (q *Queries) GetRandomHashedObjects(ctx context.Context, limit int32) ([]GetRandomHashedObjectsRow, error) {
	rows, err := q.db.Query(ctx, getRandomHashedObjects, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRandomHashedObjectsRow{}
	for rows.Next() {
		var i GetRandomHashedObjectsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.ContentHash,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionVersion,
			&i.LogicalSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertObjectLocation = `-- name: InsertObjectLocation :exec
INSERT INTO object_locations (object_key, backend_name, size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_version, logical_size, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW())
`

type InsertObjectLocationParams struct {
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
}

func (q *Queries) InsertObjectLocation(ctx context.Context, arg InsertObjectLocationParams) error {
	_, err := q.db.Exec(ctx, insertObjectLocation,
		arg.ObjectKey,
		arg.BackendName,
		arg.SizeBytes,
		arg.Encrypted,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
		arg.ContentHash,
		arg.CompressionAlgorithm,
		arg.CompressionLevel,
		arg.CompressionVersion,
		arg.LogicalSize,
	)
	return err
}

const insertObjectLocationIfNotExists = `-- name: InsertObjectLocationIfNotExists :one
INSERT INTO object_locations (object_key, backend_name, size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_version, logical_size, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW())
ON CONFLICT (object_key, backend_name) DO NOTHING
RETURNING true AS inserted
`

type InsertObjectLocationIfNotExistsParams struct {
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
}

func (q *Queries) InsertObjectLocationIfNotExists(ctx context.Context, arg InsertObjectLocationIfNotExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, insertObjectLocationIfNotExists,
		arg.ObjectKey,
		arg.BackendName,
		arg.SizeBytes,
		arg.Encrypted,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
		arg.ContentHash,
		arg.CompressionAlgorithm,
		arg.CompressionLevel,
		arg.CompressionVersion,
		arg.LogicalSize,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const listAllEncryptedLocations = `-- name: ListAllEncryptedLocations :many
SELECT object_key, backend_name, size_bytes, encryption_key, key_id, plaintext_size, compression_algorithm, compression_level, compression_version, logical_size
FROM object_locations
WHERE encrypted = TRUE
ORDER BY object_key, backend_name
LIMIT $1 OFFSET $2
`

type ListAllEncryptedLocationsParams struct {
	Limit  int32
	Offset int32
}

type ListAllEncryptedLocationsRow struct {
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
}

func (q *Queries) ListAllEncryptedLocations(ctx context.Context, arg ListAllEncryptedLocationsParams) ([]ListAllEncryptedLocationsRow, error) {
	rows, err := q.db.Query(ctx, listAllEncryptedLocations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllEncryptedLocationsRow{}
	for rows.Next() {
		var i ListAllEncryptedLocationsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionVersion,
			&i.LogicalSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectChildren = `-- name: ListDirectChildren :many
SELECT
    object_key,
    ARRAY_AGG(backend_name ORDER BY backend_name)::text[] AS backend_names,
    MAX(size_bytes)::bigint AS size_bytes,
    MIN(created_at)::timestamptz AS created_at
FROM object_locations
WHERE object_key LIKE $1::text || '%' ESCAPE '\'
  AND position('/' IN substring(object_key FROM length($1::text) + 1)) = 0
  AND length(object_key) > length($1::text)
  AND object_key > $2
GROUP BY object_key
ORDER BY object_key
LIMIT $3
`

type ListDirectChildrenParams struct {
	Prefix     string
	StartAfter string
	MaxKeys    int32
}

type ListDirectChildrenRow struct {
	ObjectKey    string
	BackendNames []string
	SizeBytes    int64
	CreatedAt    pgtype.Timestamptz
}

// Return per-file detail for non-directory children under a prefix, with pagination.
// Aggregates every replica into a sorted backend_names array per object_key so
// the file row reflects all backends a file lives on, not just one.
func (q *Queries) ListDirectChildren(ctx context.Context, arg ListDirectChildrenParams) ([]ListDirectChildrenRow, error) {
	rows, err := q.db.Query(ctx, listDirectChildren, arg.Prefix, arg.StartAfter, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectChildrenRow{}
	for rows.Next() {
		var i ListDirectChildrenRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendNames,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncryptedLocations = `-- name: ListEncryptedLocations :many
SELECT object_key, backend_name, encryption_key, key_id
FROM object_locations
WHERE encrypted = TRUE AND key_id = $1
ORDER BY object_key, backend_name
LIMIT $2 OFFSET $3
`

type ListEncryptedLocationsParams struct {
	KeyID  *string
	Limit  int32
	Offset int32
}

type ListEncryptedLocationsRow struct {
	ObjectKey     string
	BackendName   string
	EncryptionKey []byte
	KeyID         *string
}

func (q *Queries) ListEncryptedLocations(ctx context.Context, arg ListEncryptedLocationsParams) ([]ListEncryptedLocationsRow, error) {
	rows, err := q.db.Query(ctx, listEncryptedLocations, arg.KeyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEncryptedLocationsRow{}
	for rows.Next() {
		var i ListEncryptedLocationsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.EncryptionKey,
			&i.KeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredObjects = `-- name: ListExpiredObjects :many
SELECT DISTINCT ON (object_key) object_key, backend_name, size_bytes, created_at
FROM object_locations
WHERE object_key LIKE $1::text || '%' ESCAPE '\'
  AND created_at < $2
ORDER BY object_key, created_at ASC
LIMIT $3
`

type ListExpiredObjectsParams struct {
	Prefix  string
	Cutoff  pgtype.Timestamptz
	MaxKeys int32
}

type ListExpiredObjectsRow struct {
	ObjectKey   string
	BackendName string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListExpiredObjects(ctx context.Context, arg ListExpiredObjectsParams) ([]ListExpiredObjectsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredObjects, arg.Prefix, arg.Cutoff, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredObjectsRow{}
	for rows.Next() {
		var i ListExpiredObjectsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsByBackend = `-- name: ListObjectsByBackend :many
SELECT object_key, backend_name, size_bytes, created_at
FROM object_locations
WHERE backend_name = $1
ORDER BY size_bytes ASC
LIMIT $2
`

type ListObjectsByBackendParams struct {
	BackendName string
	Limit       int32
}

type ListObjectsByBackendRow struct {
	ObjectKey   string
	BackendName string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListObjectsByBackend(ctx context.Context, arg ListObjectsByBackendParams) ([]ListObjectsByBackendRow, error) {
	rows, err := q.db.Query(ctx, listObjectsByBackend, arg.BackendName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsByBackendRow{}
	for rows.Next() {
		var i ListObjectsByBackendRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsByBackendKeyAsc = `-- name: ListObjectsByBackendKeyAsc :many
SELECT object_key, backend_name, size_bytes, created_at
FROM object_locations
WHERE backend_name = $1 AND object_key COLLATE "C" > $2
ORDER BY object_key COLLATE "C" ASC
LIMIT $3
`

type ListObjectsByBackendKeyAscParams struct {
	BackendName string
	ObjectKey   string
	Limit       int32
}

type ListObjectsByBackendKeyAscRow struct {
	ObjectKey   string
	BackendName string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

// ListObjectsByBackendKeyAsc returns rows for a backend in ascending object_key
// order, starting strictly after the supplied cursor. Used by ReconcileBackend
// to drive a bounded-memory sorted-merge join against an S3 ListObjects walk.
// Pass ” as the cursor on the first call.
//
// COLLATE "C" is required: the merge join compares keys in byte order (Go string
// comparison) against S3 ListObjectsV2, which is UTF-8 byte ordered. Without it,
// a locale-collated object_key column orders the cursor differently, the merge
// mis-pairs keys, and reconcile oscillates (false imports/removes that never
// converge). The cursor predicate and ORDER BY must use the same collation.
func (q *Queries) ListObjectsByBackendKeyAsc(ctx context.Context, arg ListObjectsByBackendKeyAscParams) ([]ListObjectsByBackendKeyAscRow, error) {
	rows, err := q.db.Query(ctx, listObjectsByBackendKeyAsc, arg.BackendName, arg.ObjectKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsByBackendKeyAscRow{}
	for rows.Next() {
		var i ListObjectsByBackendKeyAscRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsByPrefix = `-- name: ListObjectsByPrefix :many
SELECT DISTINCT ON (object_key) object_key, backend_name, COALESCE(logical_size, plaintext_size, size_bytes)::bigint AS size_bytes, created_at
FROM object_locations
WHERE object_key LIKE $1::text || '%' ESCAPE '\'
  AND object_key > $2
ORDER BY object_key, created_at ASC
LIMIT $3
`

type ListObjectsByPrefixParams struct {
	Prefix     string
	StartAfter string
	MaxKeys    int32
}

type ListObjectsByPrefixRow struct {
	ObjectKey   string
	BackendName string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListObjectsByPrefix(ctx context.Context, arg ListObjectsByPrefixParams) ([]ListObjectsByPrefixRow, error) {
	rows, err := q.db.Query(ctx, listObjectsByPrefix, arg.Prefix, arg.StartAfter, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsByPrefixRow{}
	for rows.Next() {
		var i ListObjectsByPrefixRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsDelimited = `-- name: ListObjectsDelimited :many
WITH RECURSIVE walk(k) AS (
    (SELECT object_key
       FROM object_locations
      WHERE object_key LIKE $4::text || '%' ESCAPE '\'
        AND object_key COLLATE "C" > $5::text
      ORDER BY object_key COLLATE "C"
      LIMIT 1)
    UNION ALL
    SELECT (
        SELECT object_key
          FROM object_locations
         WHERE object_key LIKE $4::text || '%' ESCAPE '\'
           AND object_key COLLATE "C" > CASE
            WHEN position($2::text IN substr(walk.k, length($1::text) + 1)) > 0 THEN
                substr(walk.k, 1, length($1::text) + position($2::text IN substr(walk.k, length($1::text) + 1)) + length($2::text) - 2)
                || chr(ascii(substr(walk.k, length($1::text) + position($2::text IN substr(walk.k, length($1::text) + 1)) + length($2::text) - 1, 1)) + 1)
            ELSE walk.k
           END
         ORDER BY object_key COLLATE "C"
         LIMIT 1
    )
    FROM walk WHERE walk.k IS NOT NULL
)
SELECT
    w.k::text AS object_key,
    (position($2::text IN substr(w.k, length($1::text) + 1)) > 0)::boolean AS is_prefix,
    (CASE WHEN position($2::text IN substr(w.k, length($1::text) + 1)) > 0
        THEN substr(w.k, 1, length($1::text) + position($2::text IN substr(w.k, length($1::text) + 1)) + length($2::text) - 1)
        ELSE '' END)::text AS common_prefix,
    (CASE WHEN position($2::text IN substr(w.k, length($1::text) + 1)) > 0 THEN
            substr(w.k, 1, length($1::text) + position($2::text IN substr(w.k, length($1::text) + 1)) + length($2::text) - 2)
            || chr(ascii(substr(w.k, length($1::text) + position($2::text IN substr(w.k, length($1::text) + 1)) + length($2::text) - 1, 1)) + 1)
        ELSE w.k END)::text AS skip_bound,
    COALESCE(leaf.backend_name, '')::text AS backend_name,
    COALESCE(leaf.size_bytes, 0)::bigint AS size_bytes,
    COALESCE(leaf.created_at, to_timestamp(0)) AS created_at
FROM walk w
LEFT JOIN LATERAL (
    SELECT backend_name, COALESCE(logical_size, plaintext_size, size_bytes)::bigint AS size_bytes, created_at
      FROM object_locations o2
     WHERE o2.object_key = w.k
       AND position($2::text IN substr(w.k, length($1::text) + 1)) = 0
     ORDER BY created_at ASC
     LIMIT 1
) leaf ON true
WHERE w.k IS NOT NULL
ORDER BY w.k COLLATE "C"
LIMIT $3::int
`

type ListObjectsDelimitedParams struct {
	Prefix     string
	Delim      string
	Lim        int32
	Escprefix  string
	StartAfter string
}

type ListObjectsDelimitedRow struct {
	ObjectKey    string
	IsPrefix     bool
	CommonPrefix string
	SkipBound    string
	BackendName  string
	SizeBytes    int64
	CreatedAt    pgtype.Timestamptz
}

// Every projected column is forced non-null (empty string / 0 / epoch) because
// the built-in sqlc analyzer cannot infer nullability for computed and
// LATERAL-joined columns; the Go side uses is_prefix to pick the meaningful
// fields per row, so the placeholder values for the other branch are ignored.
func (q *Queries) ListObjectsDelimited(ctx context.Context, arg ListObjectsDelimitedParams) ([]ListObjectsDelimitedRow, error) {
	rows, err := q.db.Query(ctx, listObjectsDelimited,
		arg.Prefix,
		arg.Delim,
		arg.Lim,
		arg.Escprefix,
		arg.StartAfter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsDelimitedRow{}
	for rows.Next() {
		var i ListObjectsDelimitedRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.IsPrefix,
			&i.CommonPrefix,
			&i.SkipBound,
			&i.BackendName,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnencryptedLocations = `-- name: ListUnencryptedLocations :many
SELECT object_key, backend_name, size_bytes, compression_algorithm, compression_level, compression_version, logical_size
FROM object_locations
WHERE encrypted = FALSE
ORDER BY object_key, backend_name
LIMIT $1 OFFSET $2
`

type ListUnencryptedLocationsParams struct {
	Limit  int32
	Offset int32
}

type ListUnencryptedLocationsRow struct {
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
}

func (q *Queries) ListUnencryptedLocations(ctx context.Context, arg ListUnencryptedLocationsParams) ([]ListUnencryptedLocationsRow, error) {
	rows, err := q.db.Query(ctx, listUnencryptedLocations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnencryptedLocationsRow{}
	for rows.Next() {
		var i ListUnencryptedLocationsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionVersion,
			&i.LogicalSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockObjectKeyForWrite = `-- name: LockObjectKeyForWrite :exec

SELECT pg_advisory_xact_lock(hashtext($1))
`

// -----------------------------------------------------------------------------
// Object Location Queries
//
// Author: Alex Freidah
//
// sqlc-input definitions for object_locations - the canonical (object_key,
// backend_name) ledger of which backends hold which objects. Includes the
// transactional advisory lock primitive (LockObjectKeyForWrite) used by the
// write path, the FOR UPDATE locks used by the per-key transactional helpers
// in core/, and the listing queries the manager and dashboard consume.
// -----------------------------------------------------------------------------
func (q *Queries) LockObjectKeyForWrite(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, lockObjectKeyForWrite, hashtext)
	return err
}

const lockObjectOnBackend = `-- name: LockObjectOnBackend :one
SELECT size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_version, logical_size
FROM object_locations
WHERE object_key = $1 AND backend_name = $2
FOR UPDATE
`

type LockObjectOnBackendParams struct {
	ObjectKey   string
	BackendName string
}

type LockObjectOnBackendRow struct {
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
}

func (q *Queries) LockObjectOnBackend(ctx context.Context, arg LockObjectOnBackendParams) (LockObjectOnBackendRow, error) {
	row := q.db.QueryRow(ctx, lockObjectOnBackend, arg.ObjectKey, arg.BackendName)
	var i LockObjectOnBackendRow
	err := row.Scan(
		&i.SizeBytes,
		&i.Encrypted,
		&i.EncryptionKey,
		&i.KeyID,
		&i.PlaintextSize,
		&i.ContentHash,
		&i.CompressionAlgorithm,
		&i.CompressionLevel,
		&i.CompressionVersion,
		&i.LogicalSize,
	)
	return i, err
}

const markObjectDecrypted = `-- name: MarkObjectDecrypted :exec
UPDATE object_locations
SET encrypted = FALSE,
    encryption_key = NULL,
    key_id = NULL,
    size_bytes = $3,
    plaintext_size = NULL
WHERE object_key = $1 AND backend_name = $2
`

type MarkObjectDecryptedParams struct {
	ObjectKey   string
	BackendName string
	SizeBytes   int64
}

func (q *Queries) MarkObjectDecrypted(ctx context.Context, arg MarkObjectDecryptedParams) error {
	_, err := q.db.Exec(ctx, markObjectDecrypted, arg.ObjectKey, arg.BackendName, arg.SizeBytes)
	return err
}

const markObjectEncrypted = `-- name: MarkObjectEncrypted :exec
UPDATE object_locations
SET encrypted = TRUE,
    encryption_key = $3,
    key_id = $4,
    plaintext_size = $5,
    size_bytes = $6
WHERE object_key = $1 AND backend_name = $2
`

type MarkObjectEncryptedParams struct {
	ObjectKey     string
	BackendName   string
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
	SizeBytes     int64
}

func (q *Queries) MarkObjectEncrypted(ctx context.Context, arg MarkObjectEncryptedParams) error {
	_, err := q.db.Exec(ctx, markObjectEncrypted,
		arg.ObjectKey,
		arg.BackendName,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
		arg.SizeBytes,
	)
	return err
}

const updateContentHash = `-- name: UpdateContentHash :exec
UPDATE object_locations
SET content_hash = $3
WHERE object_key = $1 AND backend_name = $2
`

type UpdateContentHashParams struct {
	ObjectKey   string
	BackendName string
	ContentHash *string
}

func (q *Queries) UpdateContentHash(ctx context.Context, arg UpdateContentHashParams) error {
	_, err := q.db.Exec(ctx, updateContentHash, arg.ObjectKey, arg.BackendName, arg.ContentHash)
	return err
}

const updateEncryptionKey = `-- name: UpdateEncryptionKey :exec
UPDATE object_locations
SET encryption_key = $3, key_id = $4
WHERE object_key = $1 AND backend_name = $2
`

type UpdateEncryptionKeyParams struct {
	ObjectKey     string
	BackendName   string
	EncryptionKey []byte
	KeyID         *string
}

func (q *Queries) UpdateEncryptionKey(ctx context.Context, arg UpdateEncryptionKeyParams) error {
	_, err := q.db.Exec(ctx, updateEncryptionKey,
		arg.ObjectKey,
		arg.BackendName,
		arg.EncryptionKey,
		arg.KeyID,
	)
	return err
}
