// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingObjects = `-- name: CountPendingObjects :one
SELECT COUNT(*)::bigint FROM pending_objects
`

func (q *Queries) CountPendingObjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingObjects)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deletePendingObject = `-- name: DeletePendingObject :exec
DELETE FROM pending_objects WHERE intent_id = $1
`

func (q *Queries) DeletePendingObject(ctx context.Context, intentID string) error {
	_, err := q.db.Exec(ctx, deletePendingObject, intentID)
	return err
}

const deletePendingObjectsByBackend = `-- name: DeletePendingObjectsByBackend :exec
DELETE FROM pending_objects WHERE backend_name = $1
`

// Used during backend remove/drain finalization so abandoned intents do not
// outlive their backend's row in backend_quotas (FK cascade safety).
func (q *Queries) DeletePendingObjectsByBackend(ctx context.Context, backendName string) error {
	_, err := q.db.Exec(ctx, deletePendingObjectsByBackend, backendName)
	return err
}

const getStalePendingObjects = `-- name: GetStalePendingObjects :many
SELECT intent_id, object_key, backend_name, size_bytes,
       encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_version, logical_size, created_at
FROM pending_objects
WHERE created_at <= $1
ORDER BY created_at ASC
LIMIT $2
`

type GetStalePendingObjectsParams struct {
	OlderThan pgtype.Timestamptz
	MaxKeys   int32
}

type GetStalePendingObjectsRow struct {
	IntentID             string
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
	CreatedAt            pgtype.Timestamptz
}

// Return pending intents older than @older_than for reaper resolution.
// Bounded by @max_keys per call so a backlog cannot starve other queries.
func (q *Queries) GetStalePendingObjects(ctx context.Context, arg GetStalePendingObjectsParams) ([]GetStalePendingObjectsRow, error) {
	rows, err := q.db.Query(ctx, getStalePendingObjects, arg.OlderThan, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStalePendingObjectsRow{}
	for rows.Next() {
		var i GetStalePendingObjectsRow
		if err := rows.Scan(
			&i.IntentID,
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.ContentHash,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionVersion,
			&i.LogicalSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPendingObject = `-- name: InsertPendingObject :exec

INSERT INTO pending_objects (
    intent_id, object_key, backend_name, size_bytes,
    encrypted, encryption_key, key_id, plaintext_size, content_hash,
    compression_algorithm, compression_level, compression_version, logical_size
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertPendingObjectParams struct {
	IntentID             string
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
}

// -----------------------------------------------------------------------------
// Pending Object Queries
//
// Author: Alex Freidah
//
// sqlc-input definitions for pending_objects - the in-flight PUT intent
// table that backs the PUT-before-COMMIT write-path pattern. Covers
// inserting an intent, atomically claiming and resolving it, and the
// timestamp-aware reaper scan that finds stale rows surviving a failed
// metadata commit.
// -----------------------------------------------------------------------------
func (q *Queries) InsertPendingObject(ctx context.Context, arg InsertPendingObjectParams) error {
	_, err := q.db.Exec(ctx, insertPendingObject,
		arg.IntentID,
		arg.ObjectKey,
		arg.BackendName,
		arg.SizeBytes,
		arg.Encrypted,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
		arg.ContentHash,
		arg.CompressionAlgorithm,
		arg.CompressionLevel,
		arg.CompressionVersion,
		arg.LogicalSize,
	)
	return err
}

const lockPendingForUpdate = `-- name: LockPendingForUpdate :one
SELECT intent_id, object_key, backend_name, size_bytes,
       encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_version, logical_size, created_at
FROM pending_objects
WHERE intent_id = $1
FOR UPDATE
`

type LockPendingForUpdateRow struct {
	IntentID             string
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
	CreatedAt            pgtype.Timestamptz
}

// Returns the pending row under FOR UPDATE so two concurrent reapers cannot
// both attempt to promote the same intent. pgx.ErrNoRows means another
// instance already resolved this intent (deleted the row); the caller
// treats that as a benign no-op.
func (q *Queries) LockPendingForUpdate(ctx context.Context, intentID string) (LockPendingForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockPendingForUpdate, intentID)
	var i LockPendingForUpdateRow
	err := row.Scan(
		&i.IntentID,
		&i.ObjectKey,
		&i.BackendName,
		&i.SizeBytes,
		&i.Encrypted,
		&i.EncryptionKey,
		&i.KeyID,
		&i.PlaintextSize,
		&i.ContentHash,
		&i.CompressionAlgorithm,
		&i.CompressionLevel,
		&i.CompressionVersion,
		&i.LogicalSize,
		&i.CreatedAt,
	)
	return i, err
}
