// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provisioning.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBucket = `-- name: CreateBucket :exec
INSERT INTO buckets (name, max_multipart_uploads, cors)
VALUES ($1, $2, $3)
`

type CreateBucketParams struct {
	Name                string
	MaxMultipartUploads int32
	Cors                []byte
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) error {
	_, err := q.db.Exec(ctx, createBucket, arg.Name, arg.MaxMultipartUploads, arg.Cors)
	return err
}

const createCredential = `-- name: CreateCredential :exec
INSERT INTO credentials (access_key_id, user_id, secret, label, disabled)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCredentialParams struct {
	AccessKeyID string
	UserID      string
	Secret      string
	Label       *string
	Disabled    bool
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential,
		arg.AccessKeyID,
		arg.UserID,
		arg.Secret,
		arg.Label,
		arg.Disabled,
	)
	return err
}

const createGrant = `-- name: CreateGrant :exec
INSERT INTO grants (user_id, resource_kind, resource_name, permissions)
VALUES ($1, $2, $3, $4)
`

type CreateGrantParams struct {
	UserID       string
	ResourceKind string
	ResourceName string
	Permissions  string
}

// permissions is the comma-separated set the grant carries; empty means all of
// them, which is what every grant written before permissions existed holds.
func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) error {
	_, err := q.db.Exec(ctx, createGrant,
		arg.UserID,
		arg.ResourceKind,
		arg.ResourceName,
		arg.Permissions,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, name)
VALUES ($1, $2)
`

type CreateUserParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.Name)
	return err
}

const deleteBucket = `-- name: DeleteBucket :exec
DELETE FROM buckets WHERE name = $1
`

// Objects stored under the bucket are untouched, so a caller that means to
// destroy data does that first.
func (q *Queries) DeleteBucket(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteBucket, name)
	return err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE access_key_id = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, accessKeyID string) error {
	_, err := q.db.Exec(ctx, deleteCredential, accessKeyID)
	return err
}

const deleteGrant = `-- name: DeleteGrant :exec
DELETE FROM grants
WHERE user_id = $1 AND resource_kind = $2 AND resource_name = $3
`

type DeleteGrantParams struct {
	UserID       string
	ResourceKind string
	ResourceName string
}

func (q *Queries) DeleteGrant(ctx context.Context, arg DeleteGrantParams) error {
	_, err := q.db.Exec(ctx, deleteGrant, arg.UserID, arg.ResourceKind, arg.ResourceName)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

// Refused by the foreign keys while the user still holds credentials or grants,
// so those are removed first and revocation stays an explicit act.
func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const listBuckets = `-- name: ListBuckets :many

SELECT name, max_multipart_uploads, cors, created_at
FROM buckets
ORDER BY name
`

// -----------------------------------------------------------------------------
// Provisioning Queries
//
// Author: Alex Freidah
//
// sqlc-input definitions for the store half of the bucket registry: the
// buckets, users, keypairs and grants that exist as rows rather than as config
// entries. The listings are what registry assembly reads before merging with
// what config declares; the rest is how each row comes into being and stops
// being.
//
// Every listing orders in SQL so both engines hand back the same sequence and a
// caller comparing two assemblies compares content rather than ordering.
// -----------------------------------------------------------------------------
func (q *Queries) ListBuckets(ctx context.Context) ([]Bucket, error) {
	rows, err := q.db.Query(ctx, listBuckets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bucket{}
	for rows.Next() {
		var i Bucket
		if err := rows.Scan(
			&i.Name,
			&i.MaxMultipartUploads,
			&i.Cors,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT access_key_id, user_id, secret, label, disabled, created_at, last_used_at
FROM credentials
ORDER BY access_key_id
`

// Disabled credentials are included: whether one authenticates is the
// registry's decision, and hiding them here would also hide them from the
// operator asking what exists.
func (q *Queries) ListCredentials(ctx context.Context) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.AccessKeyID,
			&i.UserID,
			&i.Secret,
			&i.Label,
			&i.Disabled,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrants = `-- name: ListGrants :many
SELECT user_id, resource_kind, resource_name, permissions, created_at
FROM grants
ORDER BY user_id, resource_kind, resource_name
`

type ListGrantsRow struct {
	UserID       string
	ResourceKind string
	ResourceName string
	Permissions  string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListGrants(ctx context.Context) ([]ListGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantsRow{}
	for rows.Next() {
		var i ListGrantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ResourceKind,
			&i.ResourceName,
			&i.Permissions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, created_at
FROM users
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameUser = `-- name: RenameUser :exec
UPDATE users SET name = $1 WHERE id = $2
`

type RenameUserParams struct {
	Name string
	ID   string
}

// The id is what credentials and grants reference, so only the name an operator
// reads changes.
func (q *Queries) RenameUser(ctx context.Context, arg RenameUserParams) error {
	_, err := q.db.Exec(ctx, renameUser, arg.Name, arg.ID)
	return err
}

const setGrant = `-- name: SetGrant :exec
INSERT INTO grants (user_id, resource_kind, resource_name, permissions)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, resource_kind, resource_name)
DO UPDATE SET permissions = EXCLUDED.permissions
`

type SetGrantParams struct {
	UserID       string
	ResourceKind string
	ResourceName string
	Permissions  string
}

// Upsert rather than update: a caller declaring what a user reaches should not
// have to know whether the grant is already there, so re-applying the same
// statement converges instead of failing the second time.
func (q *Queries) SetGrant(ctx context.Context, arg SetGrantParams) error {
	_, err := q.db.Exec(ctx, setGrant,
		arg.UserID,
		arg.ResourceKind,
		arg.ResourceName,
		arg.Permissions,
	)
	return err
}

const updateBucket = `-- name: UpdateBucket :exec
UPDATE buckets
SET max_multipart_uploads = $1, cors = $2
WHERE name = $3
`

type UpdateBucketParams struct {
	MaxMultipartUploads int32
	Cors                []byte
	Name                string
}

// The name identifies the bucket and its objects, so only what a bucket carries
// changes here. Both columns are written on every call: the caller declares
// whole state, and an omitted CORS set means the bucket now has none.
func (q *Queries) UpdateBucket(ctx context.Context, arg UpdateBucketParams) error {
	_, err := q.db.Exec(ctx, updateBucket, arg.MaxMultipartUploads, arg.Cors, arg.Name)
	return err
}
