// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quota.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustQuotaStripe = `-- name: AdjustQuotaStripe :exec
INSERT INTO backend_quota_stripes (backend_name, stripe_id, bytes_used)
VALUES ($1, $2, $3)
ON CONFLICT (backend_name, stripe_id) DO UPDATE
SET bytes_used = backend_quota_stripes.bytes_used + EXCLUDED.bytes_used
`

type AdjustQuotaStripeParams struct {
	BackendName string
	StripeID    int16
	Delta       int64
}

// Applies a signed delta to one stripe, materializing the row on first use so
// nothing has to seed a backend's stripes up front. No bytes_limit guard: the
// ceiling is enforced before the write is admitted, and a counter that declined
// to record bytes already on a backend would understate it permanently.
func (q *Queries) AdjustQuotaStripe(ctx context.Context, arg AdjustQuotaStripeParams) error {
	_, err := q.db.Exec(ctx, adjustQuotaStripe, arg.BackendName, arg.StripeID, arg.Delta)
	return err
}

const decrementOrphanBytes = `-- name: DecrementOrphanBytes :exec
UPDATE backend_quotas
SET orphan_bytes = GREATEST(0, orphan_bytes - $1), updated_at = NOW()
WHERE backend_name = $2
`

type DecrementOrphanBytesParams struct {
	Amount      int64
	BackendName string
}

func (q *Queries) DecrementOrphanBytes(ctx context.Context, arg DecrementOrphanBytesParams) error {
	_, err := q.db.Exec(ctx, decrementOrphanBytes, arg.Amount, arg.BackendName)
	return err
}

const deleteQuota = `-- name: DeleteQuota :exec
DELETE FROM backend_quotas WHERE backend_name = $1
`

func (q *Queries) DeleteQuota(ctx context.Context, backendName string) error {
	_, err := q.db.Exec(ctx, deleteQuota, backendName)
	return err
}

const getActiveMultipartCountsByBackend = `-- name: GetActiveMultipartCountsByBackend :many
SELECT backend_name, COUNT(*) AS upload_count
FROM multipart_uploads
GROUP BY backend_name
`

type GetActiveMultipartCountsByBackendRow struct {
	BackendName string
	UploadCount int64
}

func (q *Queries) GetActiveMultipartCountsByBackend(ctx context.Context) ([]GetActiveMultipartCountsByBackendRow, error) {
	rows, err := q.db.Query(ctx, getActiveMultipartCountsByBackend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveMultipartCountsByBackendRow{}
	for rows.Next() {
		var i GetActiveMultipartCountsByBackendRow
		if err := rows.Scan(&i.BackendName, &i.UploadCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllQuotaStats = `-- name: GetAllQuotaStats :many
SELECT q.backend_name,
       GREATEST(0, COALESCE(s.bytes_used, 0))::bigint AS bytes_used,
       q.bytes_limit,
       q.orphan_bytes,
       q.updated_at
FROM backend_quotas q
LEFT JOIN (
    SELECT backend_name, SUM(bytes_used) AS bytes_used
    FROM backend_quota_stripes
    GROUP BY backend_name
) s ON s.backend_name = q.backend_name
`

type GetAllQuotaStatsRow struct {
	BackendName string
	BytesUsed   int64
	BytesLimit  int64
	OrphanBytes int64
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetAllQuotaStats(ctx context.Context) ([]GetAllQuotaStatsRow, error) {
	rows, err := q.db.Query(ctx, getAllQuotaStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllQuotaStatsRow{}
	for rows.Next() {
		var i GetAllQuotaStatsRow
		if err := rows.Scan(
			&i.BackendName,
			&i.BytesUsed,
			&i.BytesLimit,
			&i.OrphanBytes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObjectCountsByBackend = `-- name: GetObjectCountsByBackend :many
SELECT backend_name, COUNT(*) AS object_count
FROM object_locations
GROUP BY backend_name
`

type GetObjectCountsByBackendRow struct {
	BackendName string
	ObjectCount int64
}

func (q *Queries) GetObjectCountsByBackend(ctx context.Context) ([]GetObjectCountsByBackendRow, error) {
	rows, err := q.db.Query(ctx, getObjectCountsByBackend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetObjectCountsByBackendRow{}
	for rows.Next() {
		var i GetObjectCountsByBackendRow
		if err := rows.Scan(&i.BackendName, &i.ObjectCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObjectSizeBytes = `-- name: GetObjectSizeBytes :one
SELECT size_bytes FROM object_locations
WHERE object_key = $1 AND backend_name = $2
`

type GetObjectSizeBytesParams struct {
	ObjectKey   string
	BackendName string
}

// Returns the current size_bytes of an object_locations row. Used
// inside MarkObjectDecrypted so the caller can compute the size
// delta against the row that is about to be overwritten without
// needing the old ciphertext size to flow through the API.
func (q *Queries) GetObjectSizeBytes(ctx context.Context, arg GetObjectSizeBytesParams) (int64, error) {
	row := q.db.QueryRow(ctx, getObjectSizeBytes, arg.ObjectKey, arg.BackendName)
	var size_bytes int64
	err := row.Scan(&size_bytes)
	return size_bytes, err
}

const getUnverifiedObjectCountsByBackend = `-- name: GetUnverifiedObjectCountsByBackend :many
SELECT backend_name, COUNT(*) AS object_count
FROM object_locations
WHERE content_hash IS NULL
GROUP BY backend_name
`

type GetUnverifiedObjectCountsByBackendRow struct {
	BackendName string
	ObjectCount int64
}

func (q *Queries) GetUnverifiedObjectCountsByBackend(ctx context.Context) ([]GetUnverifiedObjectCountsByBackendRow, error) {
	rows, err := q.db.Query(ctx, getUnverifiedObjectCountsByBackend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnverifiedObjectCountsByBackendRow{}
	for rows.Next() {
		var i GetUnverifiedObjectCountsByBackendRow
		if err := rows.Scan(&i.BackendName, &i.ObjectCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementOrphanBytes = `-- name: IncrementOrphanBytes :exec
UPDATE backend_quotas
SET orphan_bytes = orphan_bytes + $1, updated_at = NOW()
WHERE backend_name = $2
`

type IncrementOrphanBytesParams struct {
	Amount      int64
	BackendName string
}

func (q *Queries) IncrementOrphanBytes(ctx context.Context, arg IncrementOrphanBytesParams) error {
	_, err := q.db.Exec(ctx, incrementOrphanBytes, arg.Amount, arg.BackendName)
	return err
}

const listBackendQuotaUsage = `-- name: ListBackendQuotaUsage :many
SELECT q.backend_name,
       q.bytes_limit,
       GREATEST(0, COALESCE(s.bytes_used, 0))::bigint AS bytes_used,
       q.orphan_bytes,
       (COALESCE(m.inflight, 0) + COALESCE(p.inflight, 0))::bigint AS inflight_bytes
FROM backend_quotas q
LEFT JOIN (
    SELECT backend_name, SUM(bytes_used) AS bytes_used
    FROM backend_quota_stripes
    GROUP BY backend_name
) s ON s.backend_name = q.backend_name
LEFT JOIN (
    SELECT mu.backend_name, SUM(mp.size_bytes) AS inflight
    FROM multipart_uploads mu
    JOIN multipart_parts mp ON mp.upload_id = mu.upload_id
    GROUP BY mu.backend_name
) m ON m.backend_name = q.backend_name
LEFT JOIN (
    SELECT backend_name, SUM(size_bytes) AS inflight
    FROM pending_objects
    GROUP BY backend_name
) p ON p.backend_name = q.backend_name
`

type ListBackendQuotaUsageRow struct {
	BackendName   string
	BytesLimit    int64
	BytesUsed     int64
	OrphanBytes   int64
	InflightBytes int64
}

// Every backend's ceiling and what occupies it: the striped byte total, orphans
// awaiting cleanup, and the writes that have not landed yet.
//
// In-flight is the parts of incomplete multipart uploads plus the intents of
// single-object PUTs still in progress. Both describe bytes on their way to a
// backend that no object_locations row covers, and both are rows every instance
// can read - which is what makes the figure fleet-wide rather than a view of
// what this process happens to have started.
func (q *Queries) ListBackendQuotaUsage(ctx context.Context) ([]ListBackendQuotaUsageRow, error) {
	rows, err := q.db.Query(ctx, listBackendQuotaUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackendQuotaUsageRow{}
	for rows.Next() {
		var i ListBackendQuotaUsageRow
		if err := rows.Scan(
			&i.BackendName,
			&i.BytesLimit,
			&i.BytesUsed,
			&i.OrphanBytes,
			&i.InflightBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBackendBytesUsed = `-- name: SetBackendBytesUsed :exec
WITH cleared AS (
    UPDATE backend_quota_stripes
    SET bytes_used = 0
    WHERE backend_name = $1 AND stripe_id <> 0
    RETURNING 1
)
INSERT INTO backend_quota_stripes (backend_name, stripe_id, bytes_used)
VALUES ($1, 0, $2)
ON CONFLICT (backend_name, stripe_id) DO UPDATE
SET bytes_used = EXCLUDED.bytes_used
`

type SetBackendBytesUsedParams struct {
	BackendName string
	BytesUsed   int64
}

// Replaces a backend's byte total with an authoritative recomputed value by
// collapsing it onto stripe zero and clearing the rest. Reconciliation is the
// one caller: it has recomputed the total from the ledger, so the distribution
// that produced the old value carries no information worth preserving.
func (q *Queries) SetBackendBytesUsed(ctx context.Context, arg SetBackendBytesUsedParams) error {
	_, err := q.db.Exec(ctx, setBackendBytesUsed, arg.BackendName, arg.BytesUsed)
	return err
}

const sumObjectSizesByBackend = `-- name: SumObjectSizesByBackend :many
SELECT backend_name, COALESCE(SUM(size_bytes), 0)::bigint AS total_bytes
FROM object_locations
GROUP BY backend_name
`

type SumObjectSizesByBackendRow struct {
	BackendName string
	TotalBytes  int64
}

// Authoritative per-backend byte total from the object ledger. Used by usage
// reconciliation to recompute bytes_used, which is otherwise an incrementally
// maintained counter that drifts if any mutation path misses an adjustment.
func (q *Queries) SumObjectSizesByBackend(ctx context.Context) ([]SumObjectSizesByBackendRow, error) {
	rows, err := q.db.Query(ctx, sumObjectSizesByBackend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumObjectSizesByBackendRow{}
	for rows.Next() {
		var i SumObjectSizesByBackendRow
		if err := rows.Scan(&i.BackendName, &i.TotalBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertQuotaLimit = `-- name: UpsertQuotaLimit :exec

INSERT INTO backend_quotas (backend_name, bytes_limit, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (backend_name) DO UPDATE SET
    bytes_limit = $2,
    updated_at = NOW()
`

type UpsertQuotaLimitParams struct {
	BackendName string
	BytesLimit  int64
}

// -----------------------------------------------------------------------------
// Quota Queries
//
// Author: Alex Freidah
//
// sqlc-input definitions for backend_quotas - the per-backend bytes_limit and
// orphan_bytes counters - and backend_quota_stripes, which holds the stored
// byte total split across rows so concurrent writers do not contend on one.
//
// A backend's byte total is always SUM(bytes_used) over its stripes, never a
// single row, and the clamp at zero belongs on that sum: a stripe is signed and
// may sit negative while the total is correct. Lock acquisition order across
// multi-row updates is enforced at the call site (sorted backend_name) to avoid
// deadlock.
// -----------------------------------------------------------------------------
func (q *Queries) UpsertQuotaLimit(ctx context.Context, arg UpsertQuotaLimitParams) error {
	_, err := q.db.Exec(ctx, upsertQuotaLimit, arg.BackendName, arg.BytesLimit)
	return err
}
