// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replication.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOverReplicatedObjects = `-- name: CountOverReplicatedObjects :one
SELECT COUNT(*)::bigint AS count
FROM (
    SELECT object_key
    FROM object_locations
    GROUP BY object_key
    HAVING COUNT(*) > $1::bigint
) over_replicated
`

func (q *Queries) CountOverReplicatedObjects(ctx context.Context, factor int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOverReplicatedObjects, factor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOverReplicatedObjects = `-- name: GetOverReplicatedObjects :many
WITH over_replicated AS (
    SELECT object_key
    FROM object_locations
    GROUP BY object_key
    HAVING COUNT(*) > $1::bigint
    LIMIT $2
)
SELECT ol.object_key, ol.backend_name, ol.size_bytes, ol.encrypted, ol.encryption_key, ol.key_id, ol.plaintext_size, ol.content_hash, ol.compression_algorithm, ol.compression_level, ol.compression_version, ol.logical_size, ol.created_at
FROM object_locations ol
JOIN over_replicated orep ON ol.object_key = orep.object_key
ORDER BY ol.object_key ASC, ol.created_at ASC
`

type GetOverReplicatedObjectsParams struct {
	Factor  int64
	MaxKeys int32
}

type GetOverReplicatedObjectsRow struct {
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) GetOverReplicatedObjects(ctx context.Context, arg GetOverReplicatedObjectsParams) ([]GetOverReplicatedObjectsRow, error) {
	rows, err := q.db.Query(ctx, getOverReplicatedObjects, arg.Factor, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOverReplicatedObjectsRow{}
	for rows.Next() {
		var i GetOverReplicatedObjectsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.ContentHash,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionVersion,
			&i.LogicalSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnderReplicatedObjects = `-- name: GetUnderReplicatedObjects :many

WITH under_replicated AS (
    SELECT object_key
    FROM object_locations
    GROUP BY object_key
    HAVING COUNT(*) < $1::bigint
    LIMIT $2
)
SELECT ol.object_key, ol.backend_name, ol.size_bytes, ol.encrypted, ol.encryption_key, ol.key_id, ol.plaintext_size, ol.content_hash, ol.compression_algorithm, ol.compression_level, ol.compression_version, ol.logical_size, ol.created_at
FROM object_locations ol
JOIN under_replicated ur ON ol.object_key = ur.object_key
ORDER BY ol.object_key ASC, ol.created_at ASC
`

type GetUnderReplicatedObjectsParams struct {
	Factor  int64
	MaxKeys int32
}

type GetUnderReplicatedObjectsRow struct {
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
	CreatedAt            pgtype.Timestamptz
}

// -----------------------------------------------------------------------------
// Replication Queries
//
// Author: Alex Freidah
//
// sqlc-input definitions backing the replicator and over-replication
// cleaner: under-replicated and over-replicated scans, the conditional
// replica insert that returns the source row's size_bytes, and the
// excess-copy removal. The "excluding" variant of the under-replicated
// scan lets workers skip backends that are draining or circuit-broken.
// -----------------------------------------------------------------------------
func (q *Queries) GetUnderReplicatedObjects(ctx context.Context, arg GetUnderReplicatedObjectsParams) ([]GetUnderReplicatedObjectsRow, error) {
	rows, err := q.db.Query(ctx, getUnderReplicatedObjects, arg.Factor, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnderReplicatedObjectsRow{}
	for rows.Next() {
		var i GetUnderReplicatedObjectsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.ContentHash,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionVersion,
			&i.LogicalSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnderReplicatedObjectsExcluding = `-- name: GetUnderReplicatedObjectsExcluding :many
WITH under_replicated AS (
    SELECT object_key
    FROM object_locations
    WHERE backend_name != ALL($1::text[])
    GROUP BY object_key
    HAVING COUNT(*) < $2::bigint
    LIMIT $3
)
SELECT ol.object_key, ol.backend_name, ol.size_bytes, ol.encrypted, ol.encryption_key, ol.key_id, ol.plaintext_size, ol.content_hash, ol.compression_algorithm, ol.compression_level, ol.compression_version, ol.logical_size, ol.created_at
FROM object_locations ol
JOIN under_replicated ur ON ol.object_key = ur.object_key
ORDER BY ol.object_key ASC, ol.created_at ASC
`

type GetUnderReplicatedObjectsExcludingParams struct {
	Excluded []string
	Factor   int64
	MaxKeys  int32
}

type GetUnderReplicatedObjectsExcludingRow struct {
	ObjectKey            string
	BackendName          string
	SizeBytes            int64
	Encrypted            bool
	EncryptionKey        []byte
	KeyID                *string
	PlaintextSize        *int64
	ContentHash          *string
	CompressionAlgorithm *string
	CompressionLevel     *int32
	CompressionVersion   *int32
	LogicalSize          *int64
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) GetUnderReplicatedObjectsExcluding(ctx context.Context, arg GetUnderReplicatedObjectsExcludingParams) ([]GetUnderReplicatedObjectsExcludingRow, error) {
	rows, err := q.db.Query(ctx, getUnderReplicatedObjectsExcluding, arg.Excluded, arg.Factor, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnderReplicatedObjectsExcludingRow{}
	for rows.Next() {
		var i GetUnderReplicatedObjectsExcludingRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.ContentHash,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionVersion,
			&i.LogicalSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReplicaConditional = `-- name: InsertReplicaConditional :one
INSERT INTO object_locations (object_key, backend_name, size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_version, logical_size, created_at)
SELECT $1, $2, ol.size_bytes, ol.encrypted, ol.encryption_key, ol.key_id, ol.plaintext_size, ol.content_hash, ol.compression_algorithm, ol.compression_level, ol.compression_version, ol.logical_size, NOW()
FROM object_locations ol
WHERE ol.object_key = $1 AND ol.backend_name = $3
ON CONFLICT (object_key, backend_name) DO NOTHING
RETURNING size_bytes
`

type InsertReplicaConditionalParams struct {
	ObjectKey     string
	BackendName   string
	BackendName_2 string
}

// Returns the size_bytes that was actually inserted into object_locations
// (read from the source row in the same statement). Caller uses this size
// for IncrementBackendQuota so object_locations.size_bytes and
// backend_quotas.bytes_used always agree, even if the in-memory copy size
// the caller observed before InsertReplicaConditional differs from the
// source row's current size_bytes (e.g. a concurrent overwrite landed
// between GetUnderReplicatedObjects and the conditional insert).
// ON CONFLICT or missing source returns no rows; the caller treats that
// as inserted=false.
func (q *Queries) InsertReplicaConditional(ctx context.Context, arg InsertReplicaConditionalParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReplicaConditional, arg.ObjectKey, arg.BackendName, arg.BackendName_2)
	var size_bytes int64
	err := row.Scan(&size_bytes)
	return size_bytes, err
}
