// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
)

const countObjectTags = `-- name: CountObjectTags :one
SELECT count(*)
FROM object_tags
WHERE object_key = $1
`

// Serves the tagging-count header on the read path, which needs the size of
// the set rather than its contents. The object_tags primary key leads with
// object_key, so this is an index-only scan over the one key's rows.
func (q *Queries) CountObjectTags(ctx context.Context, objectKey string) (int64, error) {
	row := q.db.QueryRow(ctx, countObjectTags, objectKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteObjectTags = `-- name: DeleteObjectTags :exec
DELETE FROM object_tags
WHERE object_key = $1
`

func (q *Queries) DeleteObjectTags(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, deleteObjectTags, objectKey)
	return err
}

const deleteObjectTagsForKeys = `-- name: DeleteObjectTagsForKeys :exec
DELETE FROM object_tags
WHERE object_key = ANY($1::text[])
`

// Batch form for the multi-key delete path. One statement rather than a
// statement per key, matching how DeleteObjectsByKeys removes the locations.
func (q *Queries) DeleteObjectTagsForKeys(ctx context.Context, objectKeys []string) error {
	_, err := q.db.Exec(ctx, deleteObjectTagsForKeys, objectKeys)
	return err
}

const getObjectTags = `-- name: GetObjectTags :many

SELECT tag_key, tag_value
FROM object_tags
WHERE object_key = $1
ORDER BY tag_key
`

type GetObjectTagsRow struct {
	TagKey   string
	TagValue string
}

// -----------------------------------------------------------------------------
// Object Tag Queries
//
// Author: Alex Freidah
//
// sqlc-input definitions for object_tags - the S3 object tag set, keyed by
// object rather than by copy. Covers reading a set, replacing one (as a
// delete plus per-tag insert composed in core), and the clears that run
// wherever a key stops holding the object it held.
// -----------------------------------------------------------------------------
// Ordered by key so the Tagging XML response is byte-identical run to run.
// An unordered result varies with physical row order and flakes the tests.
func (q *Queries) GetObjectTags(ctx context.Context, objectKey string) ([]GetObjectTagsRow, error) {
	rows, err := q.db.Query(ctx, getObjectTags, objectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetObjectTagsRow{}
	for rows.Next() {
		var i GetObjectTagsRow
		if err := rows.Scan(&i.TagKey, &i.TagValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertObjectTag = `-- name: InsertObjectTag :exec
INSERT INTO object_tags (object_key, tag_key, tag_value)
VALUES ($1, $2, $3)
`

type InsertObjectTagParams struct {
	ObjectKey string
	TagKey    string
	TagValue  string
}

// Replace semantics are a delete followed by these inserts inside one
// transaction, so a conflict here means the caller passed a duplicate key
// and should surface as an error rather than being silently absorbed.
func (q *Queries) InsertObjectTag(ctx context.Context, arg InsertObjectTagParams) error {
	_, err := q.db.Exec(ctx, insertObjectTag, arg.ObjectKey, arg.TagKey, arg.TagValue)
	return err
}
