// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package db

import (
	"context"
)

const deletePoolUsageByBackend = `-- name: DeletePoolUsageByBackend :exec
DELETE FROM backend_request_usage WHERE backend_name = $1
`

func (q *Queries) DeletePoolUsageByBackend(ctx context.Context, backendName string) error {
	_, err := q.db.Exec(ctx, deletePoolUsageByBackend, backendName)
	return err
}

const deleteUsageByBackend = `-- name: DeleteUsageByBackend :exec
DELETE FROM backend_usage WHERE backend_name = $1
`

func (q *Queries) DeleteUsageByBackend(ctx context.Context, backendName string) error {
	_, err := q.db.Exec(ctx, deleteUsageByBackend, backendName)
	return err
}

const flushPoolDelta = `-- name: FlushPoolDelta :exec
INSERT INTO backend_request_usage (backend_name, period, pool, requests, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (backend_name, period, pool) DO UPDATE SET
    requests   = backend_request_usage.requests + $4,
    updated_at = NOW()
`

type FlushPoolDeltaParams struct {
	BackendName string
	Period      string
	Pool        string
	Requests    int64
}

// Adds one pool's accumulated delta to its persistent row, creating the row on
// first charge in the period. Same additive ON CONFLICT as the totals above so
// concurrent flushers converge.
func (q *Queries) FlushPoolDelta(ctx context.Context, arg FlushPoolDeltaParams) error {
	_, err := q.db.Exec(ctx, flushPoolDelta,
		arg.BackendName,
		arg.Period,
		arg.Pool,
		arg.Requests,
	)
	return err
}

const flushUsageDeltas = `-- name: FlushUsageDeltas :exec

INSERT INTO backend_usage (backend_name, period, api_requests, egress_bytes, ingress_bytes, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (backend_name, period) DO UPDATE SET
    api_requests  = backend_usage.api_requests  + $3,
    egress_bytes  = backend_usage.egress_bytes  + $4,
    ingress_bytes = backend_usage.ingress_bytes + $5,
    updated_at    = NOW()
`

type FlushUsageDeltasParams struct {
	BackendName  string
	Period       string
	ApiRequests  int64
	EgressBytes  int64
	IngressBytes int64
}

// -----------------------------------------------------------------------------
// Usage Queries
//
// Author: Alex Freidah
//
// sqlc-input definitions for backend_usage - the monthly per-backend
// (api_requests, egress_bytes, ingress_bytes) counters used by the usage
// flusher and the dashboard. FlushUsageDeltas uses INSERT ON CONFLICT DO
// UPDATE with column-level ADDs so multiple flushers can converge on the
// same row without losing deltas.
// -----------------------------------------------------------------------------
// Atomically adds accumulated in-memory deltas to the persistent usage row.
// Creates the row if it doesn't exist for this (backend, period) yet.
func (q *Queries) FlushUsageDeltas(ctx context.Context, arg FlushUsageDeltasParams) error {
	_, err := q.db.Exec(ctx, flushUsageDeltas,
		arg.BackendName,
		arg.Period,
		arg.ApiRequests,
		arg.EgressBytes,
		arg.IngressBytes,
	)
	return err
}

const getPoolUsageForPeriod = `-- name: GetPoolUsageForPeriod :many
SELECT backend_name, pool, requests
FROM backend_request_usage
WHERE period = $1
`

type GetPoolUsageForPeriodRow struct {
	BackendName string
	Pool        string
	Requests    int64
}

// Returns every pool's request count for every backend in the given period.
func (q *Queries) GetPoolUsageForPeriod(ctx context.Context, period string) ([]GetPoolUsageForPeriodRow, error) {
	rows, err := q.db.Query(ctx, getPoolUsageForPeriod, period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPoolUsageForPeriodRow{}
	for rows.Next() {
		var i GetPoolUsageForPeriodRow
		if err := rows.Scan(&i.BackendName, &i.Pool, &i.Requests); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageForPeriod = `-- name: GetUsageForPeriod :many
SELECT backend_name, api_requests, egress_bytes, ingress_bytes
FROM backend_usage
WHERE period = $1
`

type GetUsageForPeriodRow struct {
	BackendName  string
	ApiRequests  int64
	EgressBytes  int64
	IngressBytes int64
}

// Returns usage stats for all backends in the given period (e.g. '2026-02').
func (q *Queries) GetUsageForPeriod(ctx context.Context, period string) ([]GetUsageForPeriodRow, error) {
	rows, err := q.db.Query(ctx, getUsageForPeriod, period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageForPeriodRow{}
	for rows.Next() {
		var i GetUsageForPeriodRow
		if err := rows.Scan(
			&i.BackendName,
			&i.ApiRequests,
			&i.EgressBytes,
			&i.IngressBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
