// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/transport/admin (interfaces: BackendOps,DashboardReader,Reconciler)
//
// Generated by this command:
//
//	mockgen -destination=mock_deps_test.go -package=admin github.com/afreidah/s3-orchestrator/internal/transport/admin BackendOps,DashboardReader,Reconciler
//

// Package admin is a generated GoMock package.
package admin

import (
	context "context"
	reflect "reflect"

	progress "github.com/afreidah/s3-orchestrator/internal/progress"
	dashboard "github.com/afreidah/s3-orchestrator/internal/proxy/dashboard"
	worker "github.com/afreidah/s3-orchestrator/internal/worker"
	gomock "go.uber.org/mock/gomock"
)

// MockBackendOps is a mock of BackendOps interface.
type MockBackendOps struct {
	ctrl     *gomock.Controller
	recorder *MockBackendOpsMockRecorder
	isgomock struct{}
}

// MockBackendOpsMockRecorder is the mock recorder for MockBackendOps.
type MockBackendOpsMockRecorder struct {
	mock *MockBackendOps
}

// NewMockBackendOps creates a new mock instance.
func NewMockBackendOps(ctrl *gomock.Controller) *MockBackendOps {
	mock := &MockBackendOps{ctrl: ctrl}
	mock.recorder = &MockBackendOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendOps) EXPECT() *MockBackendOpsMockRecorder {
	return m.recorder
}

// FlushUsage mocks base method.
func (m *MockBackendOps) FlushUsage(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushUsage", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushUsage indicates an expected call of FlushUsage.
func (mr *MockBackendOpsMockRecorder) FlushUsage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushUsage", reflect.TypeOf((*MockBackendOps)(nil).FlushUsage), ctx)
}

// ReconcileUsage mocks base method.
func (m *MockBackendOps) ReconcileUsage(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileUsage", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconcileUsage indicates an expected call of ReconcileUsage.
func (mr *MockBackendOpsMockRecorder) ReconcileUsage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileUsage", reflect.TypeOf((*MockBackendOps)(nil).ReconcileUsage), ctx)
}

// MockDashboardReader is a mock of DashboardReader interface.
type MockDashboardReader struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardReaderMockRecorder
	isgomock struct{}
}

// MockDashboardReaderMockRecorder is the mock recorder for MockDashboardReader.
type MockDashboardReaderMockRecorder struct {
	mock *MockDashboardReader
}

// NewMockDashboardReader creates a new mock instance.
func NewMockDashboardReader(ctrl *gomock.Controller) *MockDashboardReader {
	mock := &MockDashboardReader{ctrl: ctrl}
	mock.recorder = &MockDashboardReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardReader) EXPECT() *MockDashboardReaderMockRecorder {
	return m.recorder
}

// GetData mocks base method.
func (m *MockDashboardReader) GetData(ctx context.Context) (*dashboard.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", ctx)
	ret0, _ := ret[0].(*dashboard.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockDashboardReaderMockRecorder) GetData(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockDashboardReader)(nil).GetData), ctx)
}

// MockReconciler is a mock of Reconciler interface.
type MockReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockReconcilerMockRecorder
	isgomock struct{}
}

// MockReconcilerMockRecorder is the mock recorder for MockReconciler.
type MockReconcilerMockRecorder struct {
	mock *MockReconciler
}

// NewMockReconciler creates a new mock instance.
func NewMockReconciler(ctrl *gomock.Controller) *MockReconciler {
	mock := &MockReconciler{ctrl: ctrl}
	mock.recorder = &MockReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReconciler) EXPECT() *MockReconcilerMockRecorder {
	return m.recorder
}

// Reconcile mocks base method.
func (m *MockReconciler) Reconcile(ctx context.Context, backendName string) (*worker.ReconcileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, backendName)
	ret0, _ := ret[0].(*worker.ReconcileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockReconcilerMockRecorder) Reconcile(ctx, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockReconciler)(nil).Reconcile), ctx, backendName)
}

// ReconcileStreaming mocks base method.
func (m *MockReconciler) ReconcileStreaming(ctx context.Context, backendName string, observer progress.Observer) (*worker.ReconcileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileStreaming", ctx, backendName, observer)
	ret0, _ := ret[0].(*worker.ReconcileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconcileStreaming indicates an expected call of ReconcileStreaming.
func (mr *MockReconcilerMockRecorder) ReconcileStreaming(ctx, backendName, observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileStreaming", reflect.TypeOf((*MockReconciler)(nil).ReconcileStreaming), ctx, backendName, observer)
}
