// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/transport/s3api (interfaces: ObjectOps,MultipartOps)
//
// Generated by this command:
//
//	mockgen -destination=mock_ops_test.go -package=s3api github.com/afreidah/s3-orchestrator/internal/transport/s3api ObjectOps,MultipartOps
//

// Package s3api is a generated GoMock package.
package s3api

import (
	context "context"
	io "io"
	reflect "reflect"

	multipart "github.com/afreidah/s3-orchestrator/internal/proxy/multipart"
	object "github.com/afreidah/s3-orchestrator/internal/proxy/object"
	core "github.com/afreidah/s3-orchestrator/internal/store/core"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectOps is a mock of ObjectOps interface.
type MockObjectOps struct {
	ctrl     *gomock.Controller
	recorder *MockObjectOpsMockRecorder
	isgomock struct{}
}

// MockObjectOpsMockRecorder is the mock recorder for MockObjectOps.
type MockObjectOpsMockRecorder struct {
	mock *MockObjectOps
}

// NewMockObjectOps creates a new mock instance.
func NewMockObjectOps(ctrl *gomock.Controller) *MockObjectOps {
	mock := &MockObjectOps{ctrl: ctrl}
	mock.recorder = &MockObjectOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectOps) EXPECT() *MockObjectOpsMockRecorder {
	return m.recorder
}

// BackendCapacityStats mocks base method.
func (m *MockObjectOps) BackendCapacityStats(ctx context.Context) map[string]core.QuotaStat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackendCapacityStats", ctx)
	ret0, _ := ret[0].(map[string]core.QuotaStat)
	return ret0
}

// BackendCapacityStats indicates an expected call of BackendCapacityStats.
func (mr *MockObjectOpsMockRecorder) BackendCapacityStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendCapacityStats", reflect.TypeOf((*MockObjectOps)(nil).BackendCapacityStats), ctx)
}

// CanAcceptWrite mocks base method.
func (m *MockObjectOps) CanAcceptWrite(size int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanAcceptWrite", size)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanAcceptWrite indicates an expected call of CanAcceptWrite.
func (mr *MockObjectOpsMockRecorder) CanAcceptWrite(size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanAcceptWrite", reflect.TypeOf((*MockObjectOps)(nil).CanAcceptWrite), size)
}

// CopyObject mocks base method.
func (m *MockObjectOps) CopyObject(ctx context.Context, req *object.CopyObjectRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyObject", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyObject indicates an expected call of CopyObject.
func (mr *MockObjectOpsMockRecorder) CopyObject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyObject", reflect.TypeOf((*MockObjectOps)(nil).CopyObject), ctx, req)
}

// DeleteObject mocks base method.
func (m *MockObjectOps) DeleteObject(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectOpsMockRecorder) DeleteObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectOps)(nil).DeleteObject), ctx, key)
}

// DeleteObjectTags mocks base method.
func (m *MockObjectOps) DeleteObjectTags(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectTags", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectTags indicates an expected call of DeleteObjectTags.
func (mr *MockObjectOpsMockRecorder) DeleteObjectTags(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectTags", reflect.TypeOf((*MockObjectOps)(nil).DeleteObjectTags), ctx, key)
}

// DeleteObjects mocks base method.
func (m *MockObjectOps) DeleteObjects(ctx context.Context, keys []string) []object.DeleteObjectResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjects", ctx, keys)
	ret0, _ := ret[0].([]object.DeleteObjectResult)
	return ret0
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockObjectOpsMockRecorder) DeleteObjects(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjects", reflect.TypeOf((*MockObjectOps)(nil).DeleteObjects), ctx, keys)
}

// GetObject mocks base method.
func (m *MockObjectOps) GetObject(ctx context.Context, key, rangeHeader string) (*object.GetResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, key, rangeHeader)
	ret0, _ := ret[0].(*object.GetResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockObjectOpsMockRecorder) GetObject(ctx, key, rangeHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockObjectOps)(nil).GetObject), ctx, key, rangeHeader)
}

// GetObjectTags mocks base method.
func (m *MockObjectOps) GetObjectTags(ctx context.Context, key string) ([]core.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectTags", ctx, key)
	ret0, _ := ret[0].([]core.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectTags indicates an expected call of GetObjectTags.
func (mr *MockObjectOpsMockRecorder) GetObjectTags(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectTags", reflect.TypeOf((*MockObjectOps)(nil).GetObjectTags), ctx, key)
}

// HeadObject mocks base method.
func (m *MockObjectOps) HeadObject(ctx context.Context, key string) (*object.HeadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadObject", ctx, key)
	ret0, _ := ret[0].(*object.HeadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockObjectOpsMockRecorder) HeadObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadObject", reflect.TypeOf((*MockObjectOps)(nil).HeadObject), ctx, key)
}

// ListObjects mocks base method.
func (m *MockObjectOps) ListObjects(ctx context.Context, prefix, delimiter, startAfter string, maxKeys int) (*object.ListObjectsV2Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, prefix, delimiter, startAfter, maxKeys)
	ret0, _ := ret[0].(*object.ListObjectsV2Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockObjectOpsMockRecorder) ListObjects(ctx, prefix, delimiter, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockObjectOps)(nil).ListObjects), ctx, prefix, delimiter, startAfter, maxKeys)
}

// ObjectExists mocks base method.
func (m *MockObjectOps) ObjectExists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObjectExists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ObjectExists indicates an expected call of ObjectExists.
func (mr *MockObjectOpsMockRecorder) ObjectExists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObjectExists", reflect.TypeOf((*MockObjectOps)(nil).ObjectExists), ctx, key)
}

// PutObject mocks base method.
func (m *MockObjectOps) PutObject(ctx context.Context, req *object.PutObjectRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockObjectOpsMockRecorder) PutObject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockObjectOps)(nil).PutObject), ctx, req)
}

// PutObjectTags mocks base method.
func (m *MockObjectOps) PutObjectTags(ctx context.Context, key string, tags []core.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObjectTags", ctx, key, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObjectTags indicates an expected call of PutObjectTags.
func (mr *MockObjectOpsMockRecorder) PutObjectTags(ctx, key, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObjectTags", reflect.TypeOf((*MockObjectOps)(nil).PutObjectTags), ctx, key, tags)
}

// MockMultipartOps is a mock of MultipartOps interface.
type MockMultipartOps struct {
	ctrl     *gomock.Controller
	recorder *MockMultipartOpsMockRecorder
	isgomock struct{}
}

// MockMultipartOpsMockRecorder is the mock recorder for MockMultipartOps.
type MockMultipartOpsMockRecorder struct {
	mock *MockMultipartOps
}

// NewMockMultipartOps creates a new mock instance.
func NewMockMultipartOps(ctrl *gomock.Controller) *MockMultipartOps {
	mock := &MockMultipartOps{ctrl: ctrl}
	mock.recorder = &MockMultipartOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMultipartOps) EXPECT() *MockMultipartOpsMockRecorder {
	return m.recorder
}

// AbortMultipartUpload mocks base method.
func (m *MockMultipartOps) AbortMultipartUpload(ctx context.Context, bucket, key, uploadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortMultipartUpload", ctx, bucket, key, uploadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortMultipartUpload indicates an expected call of AbortMultipartUpload.
func (mr *MockMultipartOpsMockRecorder) AbortMultipartUpload(ctx, bucket, key, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortMultipartUpload", reflect.TypeOf((*MockMultipartOps)(nil).AbortMultipartUpload), ctx, bucket, key, uploadID)
}

// CompleteMultipartUpload mocks base method.
func (m *MockMultipartOps) CompleteMultipartUpload(ctx context.Context, bucket, key, uploadID string, manifest []core.CompletePart) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMultipartUpload", ctx, bucket, key, uploadID, manifest)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockMultipartOpsMockRecorder) CompleteMultipartUpload(ctx, bucket, key, uploadID, manifest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMultipartUpload", reflect.TypeOf((*MockMultipartOps)(nil).CompleteMultipartUpload), ctx, bucket, key, uploadID, manifest)
}

// CountActiveMultipartUploads mocks base method.
func (m *MockMultipartOps) CountActiveMultipartUploads(ctx context.Context, bucketPrefix string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveMultipartUploads", ctx, bucketPrefix)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveMultipartUploads indicates an expected call of CountActiveMultipartUploads.
func (mr *MockMultipartOpsMockRecorder) CountActiveMultipartUploads(ctx, bucketPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveMultipartUploads", reflect.TypeOf((*MockMultipartOps)(nil).CountActiveMultipartUploads), ctx, bucketPrefix)
}

// CreateMultipartUpload mocks base method.
func (m *MockMultipartOps) CreateMultipartUpload(ctx context.Context, req *multipart.CreateUploadRequest) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultipartUpload", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockMultipartOpsMockRecorder) CreateMultipartUpload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultipartUpload", reflect.TypeOf((*MockMultipartOps)(nil).CreateMultipartUpload), ctx, req)
}

// GetParts mocks base method.
func (m *MockMultipartOps) GetParts(ctx context.Context, bucket, key, uploadID string) ([]core.MultipartPart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParts", ctx, bucket, key, uploadID)
	ret0, _ := ret[0].([]core.MultipartPart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParts indicates an expected call of GetParts.
func (mr *MockMultipartOpsMockRecorder) GetParts(ctx, bucket, key, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParts", reflect.TypeOf((*MockMultipartOps)(nil).GetParts), ctx, bucket, key, uploadID)
}

// ListMultipartUploads mocks base method.
func (m *MockMultipartOps) ListMultipartUploads(ctx context.Context, prefix string, maxUploads int) ([]core.MultipartUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMultipartUploads", ctx, prefix, maxUploads)
	ret0, _ := ret[0].([]core.MultipartUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMultipartUploads indicates an expected call of ListMultipartUploads.
func (mr *MockMultipartOpsMockRecorder) ListMultipartUploads(ctx, prefix, maxUploads any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMultipartUploads", reflect.TypeOf((*MockMultipartOps)(nil).ListMultipartUploads), ctx, prefix, maxUploads)
}

// UploadPart mocks base method.
func (m *MockMultipartOps) UploadPart(ctx context.Context, bucket, key, uploadID string, partNumber int, body io.Reader, size int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPart", ctx, bucket, key, uploadID, partNumber, body, size)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPart indicates an expected call of UploadPart.
func (mr *MockMultipartOpsMockRecorder) UploadPart(ctx, bucket, key, uploadID, partNumber, body, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPart", reflect.TypeOf((*MockMultipartOps)(nil).UploadPart), ctx, bucket, key, uploadID, partNumber, body, size)
}
